image: node:lts

cache:
  paths:
    - node_modules
    - version.txt
    - dist

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo -e "@vdimensions:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ \n//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm install
    - npm version patch --force --no-git-tag-version
    - npm run build
    - node -e 'console.log(require("./package.json").version);' > version.txt
  allow_failure: false
  artifacts:
    paths:
      - dist
    when: on_success
  only:
    - merge_requests
    - master

publish:
  stage: deploy
  script:
    - cd dist
    - echo -e "@vdimensions:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ \n//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  only:
    - master
