image: node:lts

cache:
  paths:
    - node_modules
    - version.txt
    - dist

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - npm install
    - npm version patch --force --no-git-tag-version
    - npm run build
    - node -e 'console.log(require("./package.json").version);' > version.txt
  allow_failure: false
  artifacts:
    paths:
      - dist
    when: on_success
  only:
    - merge_requests
    - master

publish:
  stage: deploy
  script:
    - cd dist
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - npm publish
  only:
    - master
